services:
    dial-in:
        restart: unless-stopped
        container_name: dial-in-server
        image: dial-in:latest
        environment:
            - BODY_SIZE_LIMIT=20971520
            - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
            - RESEND_API_KEY=${RESEND_API_KEY}
            - EMAIL_FROM=${EMAIL_FROM:-Dial-in <noreply@dial-in.coffee>}
            - PUBLIC_BETTER_AUTH_URL=${PUBLIC_BETTER_AUTH_URL:-https://dial-in.coffee}
        networks:
            - caddy_network
        ports:
            - ${SERVICE_PORT:-3000}:3000
networks:
    caddy_network:
        driver: bridge
